version: "3"
services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBIT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBIT_PASSWORD
    ports:
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: celery_worker.dockerfile
    env_file: .env
    volumes:
      - ./:/app/
    depends_on:
      - rabbitmq
      - redis
    environment:
      - BROKER_URL=amqp://$RABBIT_USER:$RABBIT_PASSWORD@rabbitmq
      - RESULT_BACKEND=redis://redis
    working_dir: /app
    command: sh -c "celery -A apps worker -l info"