services:
  redis:
    image: redis:latest
    #    ports:
    #      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    env_file: .env
    volumes:
      - ./:/app/
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://redis/$celery_redis_db
      - RESULT_BACKEND=redis://redis/$celery_redis_db
      - CELERY_BROKER_URL=redis://redis/$celery_redis_db
      - CELERY_RESULT_BACKEND=redis://redis/$celery_redis_db
    working_dir: /app
    command: celery -A celery_app worker -l info
    restart: on-failure

  celery_beat:
    build: .
    env_file: .env
    volumes:
      - ./:/app/
    depends_on:
      - redis
      - celery_worker
    environment:
      - BROKER_URL=redis://redis/$celery_redis_db
      - RESULT_BACKEND=redis://redis/$celery_redis_db
      - CELERY_BROKER_URL=redis://redis/$celery_redis_db
      - CELERY_RESULT_BACKEND=redis://redis/$celery_redis_db
    working_dir: /app
    command: celery -A celery_app beat
    restart: on-failure


  tgbot:
    build: .
    env_file: .env
    environment:
      - redis_host=redis
    volumes:
      - ./:/app/
    depends_on:
      - redis
    working_dir: /app
    command: python main.py


volumes:
  redis_data:
